# Generated by Django 6.0.6 on 2026-06-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Helpdesk', max_length=200)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('company_tagline', models.CharField(blank=True, max_length=300)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('company_phone', models.CharField(blank=True, max_length=50)),
                ('company_website', models.URLField(blank=True)),
                ('company_address', models.TextField(blank=True)),
                ('portal_name', models.CharField(default='Helpdesk Portal', max_length=200)),
                ('portal_welcome', models.TextField(blank=True, default='Welcome! Submit and track support requests for all departments.')),
                ('support_hours', models.CharField(blank=True, default='Sunday - Thursday, 8 AM - 5 PM', max_length=200)),
                ('primary_color', models.CharField(default='#1e3a5f', help_text='Hex colour, e.g. #1e3a5f', max_length=7)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('ticket_prefix', models.CharField(default='TKT', max_length=20)),
                ('ticket_separator', models.CharField(default='-', help_text='Character between prefix, year and sequence (e.g. - or /)', max_length=5)),
                ('ticket_include_year', models.BooleanField(default=True)),
                ('ticket_year_format', models.CharField(choices=[('YYYY', 'Full year (2026)'), ('YY', 'Short year (26)')], default='YYYY', max_length=4)),
                ('ticket_seq_digits', models.PositiveIntegerField(default=5, help_text='Zero-padded sequence length (e.g. 5 -> 00001)')),
                ('ticket_reset_yearly', models.BooleanField(default=True, help_text='Reset sequence counter on 1 Jan each year')),
                ('_ticket_counter', models.PositiveIntegerField(default=0)),
                ('_ticket_counter_year', models.PositiveIntegerField(default=0)),
                ('email_sender_name', models.CharField(default='Helpdesk', max_length=200)),
                ('email_sender_address', models.EmailField(blank=True, max_length=254)),
                ('email_reply_to', models.EmailField(blank=True, max_length=254)),
                ('email_footer', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'System Settings',
            },
        ),
    ]
