# Generated by Django 6.0.6 on 2026-06-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketFormConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_required', models.BooleanField(default=True)),
                ('priority_required', models.BooleanField(default=False)),
                ('department_required', models.BooleanField(default=True)),
                ('location_required', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Ticket Form Configuration',
            },
        ),
    ]
