# Generated by Django 6.0.6 on 2026-06-29 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Leave blank for global default', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_policies', to='departments.department'),
        ),
        migrations.AlterUniqueTogether(
            name='slapolicy',
            unique_together={('department', 'priority')},
        ),
    ]
