# Generated by Django 6.0.6 on 2026-06-29 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_default_sla_policies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='auto_assign_to',
            field=models.ForeignKey(blank=True, help_text='Auto-assign new tickets in this department to this person', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_assigned_departments', to=settings.AUTH_USER_MODEL),
        ),
    ]
