# Generated by Django 6.0.6 on 2026-06-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ticket_created', 'Ticket Created'), ('ticket_updated', 'Ticket Updated'), ('ticket_assigned', 'Ticket Assigned'), ('ticket_reassigned', 'Ticket Reassigned'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('comment_added', 'Comment Added'), ('attachment_added', 'Attachment Added'), ('ticket_resolved', 'Ticket Resolved'), ('ticket_closed', 'Ticket Closed'), ('ticket_reopened', 'Ticket Reopened'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deactivated', 'User Deactivated'), ('department_created', 'Department Created'), ('department_updated', 'Department Updated'), ('login', 'User Login'), ('logout', 'User Logout')], max_length=50)),
                ('description', models.TextField()),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
